{
 "title": "Speedport Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "speedport_state" }
   ]
  },
  {
   "title": "Actual Upload",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "Kbits",
   "valueName": "avg",
   "targets": [
    {
     "expr": "speedport_actual_data_rate_kpbs{method=\"upload\"}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "speedport_attainable_data_rate_kpbs{method=\"download\"}",
     "legendFormat": "Attainable Download"
    },
    {
     "expr": "speedport_attainable_data_rate_kpbs{method=\"upload\"}",
     "legendFormat": "Attainable Upload"
    },
    {
     "expr": "speedport_actual_data_rate_kpbs{method=\"download\"}",
     "legendFormat": "Actual Download"
    },
    {
     "expr": "speedport_actual_data_rate_kpbs{method=\"upload\"}",
     "legendFormat": "Actual Upload"
    }
   ]
  },
  {
   "title": "Actual Download",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "Kbits",
   "valueName": "avg",
   "targets": [
    {
     "expr": "speedport_actual_data_rate_kpbs{method=\"download\"}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "speedport_crc_error_count" },
    { "expr": "speedport_fec_error_count" },
    { "expr": "speedport_hec_error_count" }
   ]
  },
  {
   "title": "Signal Quality",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    { "expr": "speedport_line_attenuation" },
    { "expr": "speedport_signal_level" },
    { "expr": "speedport_snr_margin" },
    {}
   ]
  }
 ]
}